version: '3'

services:

        database:
           container_name: my-database
           image: postgres
           ports:
             - "5432:5432"
           environment:
              - "POSTGRES_DB=laravel"
              - "POSTGRES_USER=laravel"
              - "POSTGRES_PASSWORD=laravel"
           volumes:
              - ./docker/postgres-data:/var/lib/postgresql/data

        php:
           build: .
           container_name: my-php
           volumes:
              - .:/api
           expose:
            - 9000

        nginx:
           image: nginx:latest
           container_name: my-nginx
           ports:
              - 80:80
           volumes:
              - ./docker/nginx:/etc/nginx/conf.d
              - ./docker/logs:/var/log/nginx
           links:
              - php
              
        composer:
           image: composer
           volumes:
              - ./api:/api

        adminer:
           container_name: my-adminer
           image: adminer
           ports:
              - 8080:8080